import { NextResponse } from "next/server";

export async function GET() {
  await new Promise((res) => setTimeout(res, 800));

  return NextResponse.json({
    data: [
      {
        id: "active_students",
        title: "Total Accounts",
        value: "145,092",
        change: "+12%",
        pricetext: "309 Accounts",
        priceicon: "/images/up-icon.svg",
        color: "text-green-5000",
        icon: "/images/user-icon.svg",
        bgcolor: "bg-gray-1300",
        iconbg: "bg-sky-5000",
      },
      {
        id: "verified_users",
        title: "Total Deposits",
        value: "€123.7M",
        change: "+1.9%",
        pricetext: "vs Last Month",
        priceicon: "/images/up-icon.svg",
        color: "text-green-5000",
        icon: "/images/deposit-icon.svg",
        bgcolor: "bg-sky-5000",
        iconbg: "bg-sky-5000",
      },
      {
        id: "amount_blocked",
        title: "Active AVI Folders",
        value: "2,847",
        change: "1.2%",
        pricetext: "vs Last Month",
        priceicon: "/images/up-icon.svg",
        color: "text-green-5000",
        icon: "/images/folder-icon.svg",
        bgcolor: "bg-sky-5000",
        iconbg: "bg-sky-5000",
      },
      {
        id: "monthly_volume",
        title: "Revenue Fees",
        value: "€456K",
        change: "+8.3%",
        pricetext: "MTD",
        priceicon: "/images/up-icon.svg",
        color: "text-green-5000",
        icon: "/images/revenue-icon.svg",
        bgcolor: "bg-gray-1300",
        iconbg: "bg-sky-5000",
      },
      {
        id: "new_subscriptions",
        title: "Blocked Accounts",
        value: "26,745",
        change: "+5.3%",
        pricetext: "This Month",
        priceicon: "/images/up-icon.svg",
        color: "text-green-5000",
        bgcolor: "bg-lightred1300",
        icon: "/images/block-icon.svg",
        iconbg: "bg-sky-5000",
      },
      {
        id: "pending_docs",
        title: "Pending Loans",
        value: "€1.42M",
        priceicon: "/images/up-icon.svg",
        pricetext: "3rd Accounts",
        change: "3.4%",
        color: "text-green-5000",
        icon: "/images/pending-icon.svg",
        bgcolor: "bg-gray-1300",
        iconbg: "bg-sky-5000",
      },
    ],
  });
}
